require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'db/**/*'

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
